apiVersion: v1
kind: Service
metadata:
  name: programas-estudios-service
spec:
  selector:
    app: programas-estudios
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP
